spring:
  application:
    name: SunApi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SUNPJ
    password: SUNPJ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hibernate:
        format_sql: true
#      spring.jpa.properties.hibernate.format_sql=true
      
          
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 1h
  port: 8787
  
mybatis:
  type-aliases-package: com.brs.sun.vo
  mapper-locations: sqls/*.xml
  configuration:
    map-underscore-to-camel-case: true