spring:
  application:
    name: SunApi
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SUNPJ
    password: SUNPJ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.Oracle12cDialect
      hibernate:
        format_sql: true
  web:
    websocket:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 15MB
          
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 1h
  port: 8787
  tomcat:
    max-http-form-post-size: 52428800 # 50MB
    max-swallow-size: 104857600  # 100MB
  
mybatis:
  type-aliases-package: com.brs.sun.vo
  mapper-locations: sqls/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
naver:
  service:
    url: "https://1wspclol7b.apigw.ntruss.com/custom/v1/33862/5eea60a9e31c041965276f764964e129d267fe46b1e43ebfcb7f1dd0e0f2d8e9/general"
    secretKey: "cWtLVWNzWnhPamJSZWxlTWVZY1ZTdG10SEF1d2pabkM="


    
